---
title: "Installation"
package: NPATools
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Installation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

NPATools requires the following packages:
```{r, include=TRUE, eval=FALSE}
BiocParallel
brainGraph
circlize
ComplexHeatmap
DOSE
ggplot2
graphics
grDevices
igraph (>= 1.5.0)
KEGGREST
Matrix
methods
openxlsx
pals
proxy
qvalue
stats
spatstat.univar
utils
```

Bioconductor packages can be installed as follows:

```{r, include=TRUE, eval=FALSE}
if (!require("BiocManager", quietly = TRUE)){
  install.packages("BiocManager")
}
BiocManager::install(c("<packagename1>", "<packagename2>", "..."))
```

CRAN packages can be installed as follows:
```{r, include=TRUE, eval=FALSE}
install.packages(c("<packagename1>", "<packagename2>", "..."))
```
  
Once all dependencies are in place, NPATools can be installed from github as follows:
```{r, include=TRUE, eval=FALSE}
devtools::install_github("emosca-cnr/NPATools")
```

To load the package:

```{r, include=TRUE, eval=FALSE}
library(NPATools)
```
